create table public.portfolio_open_positions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  import_id uuid not null references public.portfolio_imports(id) on delete cascade,
  account_currency text not null check (account_currency in ('PLN', 'EUR', 'USD')),
  product text not null,
  ticker text not null,
  instrument text not null,
  category text,
  volume numeric not null,
  report_value numeric not null,
  unique (import_id, account_currency, product, ticker)
);

alter table public.portfolio_open_positions enable row level security;
create policy "owner manages open positions" on public.portfolio_open_positions
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
grant select, insert, update, delete on public.portfolio_open_positions to authenticated;
grant usage, select on sequence public.portfolio_open_positions_id_seq to authenticated;
