alter table public.portfolio_open_positions
  add column report_profit numeric;

create table public.portfolio_open_cfd_lots (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  import_id uuid not null references public.portfolio_imports(id) on delete cascade,
  account_currency text not null check (account_currency in ('PLN', 'EUR', 'USD')),
  ticker text not null,
  position_key text not null,
  direction text not null check (direction in ('BUY', 'SELL')),
  volume numeric not null,
  open_price numeric not null,
  unique (import_id, position_key)
);

alter table public.portfolio_open_cfd_lots enable row level security;
create policy "owner manages open CFD lots" on public.portfolio_open_cfd_lots
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
grant select, insert, update, delete on public.portfolio_open_cfd_lots to authenticated;
grant usage, select on sequence public.portfolio_open_cfd_lots_id_seq to authenticated;
