create table public.portfolio_history_points (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  import_id uuid not null references public.portfolio_imports(id) on delete cascade,
  date date not null,
  base_currency text not null check (base_currency in ('PLN', 'EUR', 'USD')),
  total_value numeric not null,
  net_invested_capital numeric not null,
  total_profit numeric not null,
  source text not null default 'RECONSTRUCTED_EOD',
  unique (owner_id, date, base_currency)
);

alter table public.portfolio_history_points enable row level security;
create policy "owner manages portfolio history" on public.portfolio_history_points
  for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);
grant select, insert, update, delete on public.portfolio_history_points to authenticated;
grant usage, select on sequence public.portfolio_history_points_id_seq to authenticated;
